### ISSUE TITLE
Additional TODO v1/v2

### ISSUE THREAD

**Issue by RandyParedis** [RandyParedis/autoplay#2]
As an expansion for #1, this issue will list some additional TODO's
- [ ] Music System
    - [ ] Add support for Anacrusis
    - [ ] Add support for Triplet-like structures
- [ ] Algorithms
    - [ ] More Rhythmic Algorithms
        - [ ] MCS (Most Common Structures)
    - [ ] Dynamic Algorithms
    - [ ] Custom Algorithm Parsing/Creation
    - [ ] Algorithms for Rhythmic Instruments
- [ ] MidiPlayer
    - [ ] Force playing at all times
- [ ] Config
    - [ ] Allow full randomization of values in Config File
- [ ] Markov Chains
    - [ ] Allow appending of different chains by reading the existing csv and adding it to the to-write csv before saving.
